/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Content: typeof import('./components/Content.vue')['default']
    NCode: typeof import('naive-ui')['NCode']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDrawer: typeof import('naive-ui')['NDrawer']
    NDrawerContent: typeof import('naive-ui')['NDrawerContent']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NResult: typeof import('naive-ui')['NResult']
    NUpload: typeof import('naive-ui')['NUpload']
  }
}

// For TSX support
declare global {
  const Content: typeof import('./components/Content.vue')['default']
  const NCode: typeof import('naive-ui')['NCode']
  const NConfigProvider: typeof import('naive-ui')['NConfigProvider']
  const NDataTable: typeof import('naive-ui')['NDataTable']
  const NDialogProvider: typeof import('naive-ui')['NDialogProvider']
  const NDrawer: typeof import('naive-ui')['NDrawer']
  const NDrawerContent: typeof import('naive-ui')['NDrawerContent']
  const NLayout: typeof import('naive-ui')['NLayout']
  const NLayoutContent: typeof import('naive-ui')['NLayoutContent']
  const NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
  const NMessageProvider: typeof import('naive-ui')['NMessageProvider']
  const NResult: typeof import('naive-ui')['NResult']
  const NUpload: typeof import('naive-ui')['NUpload']
}